-- ViaHimalaya Trek POI Columns Migration
-- Adds pointers to the per-trek POI bundle generated by scripts/process_treks.py

ALTER TABLE treks ADD COLUMN IF NOT EXISTS poi_url VARCHAR(500);
ALTER TABLE treks ADD COLUMN IF NOT EXISTS poi_updated_at TIMESTAMP WITH TIME ZONE;

COMMENT ON COLUMN treks.poi_url IS
    'URL of the POI bundle on R2, e.g. https://assets.viahimalaya.com/trek_pois/<id>.json';
COMMENT ON COLUMN treks.poi_updated_at IS
    'When the bundle was last regenerated. The app compares this against its cached copy to decide whether to re-download - the R2 key never changes, so without this a refreshed bundle would never reach a device.';
